# <span style="color: #3A86FF; font-family: Georgia; font-size: 40px; text-shadow: 1px 1px 2px #A2D2FF">✨ NEURAL NETWORKS ✨</span>

A neural network in machine learning is a computational model designed to recognize patterns and make decisions based on data.
It is inspired by the structure and function of biological neurons in the human brain.Neural networks are a key component of deep learning.

Any value that we have to visualis in tensorBoard is treced by the things called summary
we created 2 different types of summary in this 1 one is called accuracy 2 one is call loss.
when we used our file writer to add the summary then we wrote the information from the summary
to our Disk .


# <span style="color: #3A86FF; font-family: Georgia; font-size: 27px; text-shadow: 1px 1px 2px #A2D2FF"> Understanding how everything fits in TensorFlow</span>

##### $TensorFlow$: Nodes :
A node represents a mathimatical operation (like addition, multiplication, matrix multiplication, etc.).
##### $TensorFlow$: Placeholder :
A placeholder is a special tensor you define in the computation graph but don’t assign a value to right away.
Instead, you feed data later when running the graph. Commonly used for inputs (training data, test data, etc.) in TensorFlow 1.x.
##### $TensorFlow$: constant :
A constant is a fixed value tensor that never changes during execution. Useful for values like learning rates, fixed matrices, etc.
##### $TensorFlow$: variables :
A variable is a tensor whose value can change during execution. Typically used for weights and biases in machine learning models.
##### $TensorFlow$: session :
A session is an environment in TensorFlow 1.x where the computation graph is executed.You first build the graph (placeholders, constants, variables, operations),then run it inside a session.
##### $TensorFlow$: feed_dictionary :
feed_dict is a dictionary that supplies actual values for placeholders when running a TensorFlow graph.

# <span style="color: #3A86FF; font-family: Georgia; font-size: 27px; text-shadow: 1px 1px 2px #A2D2FF"> Graph in TensorFlowTensorFlow </span>
##### In TensorFlow, a graph is a data structure that represents a computation. 
##### It is essentially a network (or graph) of nodes and edges.
#### $Key points$:
##### 1 The graph defines what operations will be done, not the actual results.
##### 2 You first build the graph (defining ops and tensors).
##### 3 You first build the graph (defining ops and tensors).

# <span style="color: #3A86FF; font-family: Georgia; font-size: 27px; text-shadow: 1px 1px 2px #A2D2FF"> Imports </span>

In [1]:
from numpy.random import seed
seed(888)  

import os
import numpy as np
import tensorflow as tf

tf.random.set_seed(404)  

2025-10-20 09:05:15.786794: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/opt/anaconda3/envs/tf_env/lib/python3.9/site-packages/requests/__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(


In [2]:
import os
import numpy as np
import tensorflow as tf
import tensorflow.compat.v1 as tf
from PIL import Image
from time import strftime

# <span style="color: #3A86FF; font-family: Georgia; font-size: 27px; text-shadow: 1px 1px 2px #A2D2FF">Constants</span>

In [8]:
X_TRAIN_PATH = '../mlproject/MNIST/digit_xtrain.csv'
X_TEST_PATH = '../mlproject/MNIST/digit_xtest.csv'
Y_TRAIN_PATH = '../mlproject/MNIST/digit_ytrain.csv'
Y_TEST_PATH = '../mlproject/MNIST/digit_ytest.csv'

LOGGING_PATH =  '../mlproject/tensorboard_mnist_digit_logs'

NR_CLASSES = 10
VALIDATION_SIZE = 10000
IMAGE_WIDTH = 28
IMAGE_HEIGHT = 28
CHANNELS = 1
TOTAL_INPUTS = IMAGE_WIDTH * IMAGE_HEIGHT * CHANNELS

# <span style="color: #3A86FF; font-family: Georgia; font-size: 27px; text-shadow: 1px 1px 2px #A2D2FF">Get The Data</span>

In [9]:
%%time
y_train_all = np.loadtxt(Y_TRAIN_PATH, delimiter=',',dtype=int)

CPU times: user 5.39 ms, sys: 4.99 ms, total: 10.4 ms
Wall time: 12.4 ms


In [10]:
y_train_all.shape

(60000,)

In [11]:
y_test = np.loadtxt(Y_TEST_PATH, delimiter=',',dtype=int)

In [12]:
%%time

x_train_all = np.loadtxt(X_TRAIN_PATH, delimiter=',',dtype=int)

CPU times: user 1.43 s, sys: 282 ms, total: 1.72 s
Wall time: 1.96 s


In [13]:
%%time

x_test = np.loadtxt(X_TEST_PATH, delimiter=',',dtype=int)

CPU times: user 252 ms, sys: 57.4 ms, total: 310 ms
Wall time: 345 ms



# <span style="color: #3A86FF; font-family: Georgia; font-size: 27px; text-shadow: 1px 1px 2px #A2D2FF">Explore</span>

In [14]:
x_train_all.shape

(60000, 784)

In [15]:
x_train_all[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,  18,  18,
       126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 17

In [16]:
y_train_all.shape

(60000,)

In [17]:
x_test.shape

(10000, 784)

In [18]:
y_train_all[:5]

array([5, 0, 4, 1, 9])

# <span style="color: #3A86FF; font-family: Georgia; font-size: 27px; text-shadow: 1px 1px 2px #A2D2FF">Data Preprocessing</span>

In [19]:
# Re-scale
x_train_all, x_test = x_train_all / 255.0, x_test / 255.0

### Covert Target Values To One-Hot encoding

In [20]:
values = y_train_all [:5]
np.eye(10)[values]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [21]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [22]:
np.eye(10)[2]

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
values

array([5, 0, 4, 1, 9])

In [24]:
values[4]

9

In [25]:
y_train_all = np.eye(NR_CLASSES)[y_train_all]

In [26]:
y_train_all.shape

(60000, 10)

In [27]:
y_test = np.eye(NR_CLASSES)[y_test]

In [29]:
y_test.shape

(10000, 10)

# <span style="color: #3A86FF; font-family: Georgia; font-size: 27px; text-shadow: 1px 1px 2px #A2D2FF">Create Validation Dataset From Training Data</span>

In [24]:

x_val = x_train_all[:VALIDATION_SIZE]  
y_val = y_train_all[:VALIDATION_SIZE] 


In [25]:
x_train = x_train_all[VALIDATION_SIZE:]
y_train = y_train_all[VALIDATION_SIZE:]

In [26]:
x_val.shape

(10000, 784)

In [27]:
x_train.shape

(50000, 784)

# <span style="color: #3A86FF; font-family: Georgia; font-size: 27px; text-shadow: 1px 1px 2px #A2D2FF">Set Up TensorFlow Graph</span>

In [28]:
tf.disable_v2_behavior()

X = tf.placeholder(tf.float32, shape=[None, TOTAL_INPUTS], name='X')
Y = tf.placeholder(tf.float32, shape=[None, NR_CLASSES], name='labels')


Instructions for updating:
non-resource variables are not supported in the long term


# <span style="color: #3A86FF; font-family: Georgia; font-size: 25px; text-shadow: 1px 1px 2px #A2D2FF">Neural Network Architecture</span>

# <span style="color: #3A86FF; font-family: Georgia; font-size: 22px; text-shadow: 1px 1px 2px #A2D2FF">Hyperparameters</span>


In [29]:
nr_epochs = 50
learning_rate = 1e-3

n_hidden1 = 512
n_hidden2 = 64

# [ 1 ]

# [ 2 ] 

# [ 3 ]

In [30]:
def setup_layer(input, weight_dim, bias_dim, name):
    with tf.name_scope(name):
        initial_w = tf.truncated_normal(shape=weight_dim, stddev=0.1, seed=42)
        w = tf.Variable(initial_value=initial_w, name='W') 
        
        initial_b = tf.constant(value=0.0, shape=bias_dim)
        b = tf.Variable(initial_value=initial_b, name='B')
        
        layer_in = tf.matmul(input, w) + b
        
        if name == 'out':
            layer_out = tf.nn.softmax(layer_in)
        else:
            layer_out = tf.nn.relu(layer_in)
            
            tf.summary.histogram('weights',w)
            tf.summary.histogram('biases', b)
        
        return layer_out

In [31]:
#Model Without DropOut. 

#layer_1 = setup_layer(X, weight_dim=[TOTAL_INPUTS, n_hidden1],
                      #bias_dim=[n_hidden1], name='layer_1')

#layer_2 = setup_layer(layer_1, weight_dim=[n_hidden1, n_hidden2],
                      #bias_dim=[n_hidden2], name='layer_2')

#output = setup_layer(layer_2, weight_dim=[n_hidden2, NR_CLASSES],
                     #bias_dim=[NR_CLASSES], name='out')

#model_name = f'{n_hidden1}-{n_hidden2} LR{learning_rate} E{nr_epochs}'

In [32]:
# Model with DropOut .

layer_1 = setup_layer(X, weight_dim=[TOTAL_INPUTS, n_hidden1],
                      bias_dim=[n_hidden1], name='layer_1')

Layer_drop = tf.nn.dropout(layer_1, keep_prob=0.8, name='dropout_layer')

layer_2 = setup_layer(Layer_drop, weight_dim=[n_hidden1, n_hidden2],
                      bias_dim=[n_hidden2], name='layer_2')

output = setup_layer(layer_2, weight_dim=[n_hidden2, NR_CLASSES],
                     bias_dim=[NR_CLASSES], name='out')

model_name = f'{n_hidden1}-DO-{n_hidden2} LR{learning_rate} E{nr_epochs}'

Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


##### <span style="color: #3A86FF; font-family: Georgia; font-size: 27px; text-shadow: 1px 1px 2px #A2D2FF">TensorBoard Setup</span>

In [33]:
# Folder for TensorBoard.

folder_name = f'[{model_name}] at {strftime("%H.%M")}'
directory = os.path.join(LOGGING_PATH, folder_name)

try:
    os.makedirs(directory, exist_ok=True)  
    print(f'Successfully created directory: {directory}')
except OSError as exception:
    print(f'Error creating directory: {exception.strerror}')

Successfully created directory: C:\Users\User\mlprojects\tensorboard_mnist_digit_logs\[512-DO-64 LR0.001 E50] at 15.39


### Loss, Optimisation and Metrics

### Defining Loss Function

In [34]:
with tf.name_scope('loss_calc'):
    loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(labels=Y, logits=output))

### Defining Optimizer

In [35]:
with tf.name_scope('optimizer'):
    optimizer = tf.train.AdamOptimizer(learning_rate)
    train_step = optimizer.minimize(loss)

### Accuracy Metric
any value that we have to visualis in tensorBoard is treced by the things callled summary
we created 2 different types of summary in this 1 one is called accuracy 2 one is call loss

In [36]:
with tf.name_scope('accuracy_calc'):
    model_prediction = tf.argmax(output, axis=1, name='prediction')
    correct_pred = tf.equal(model_prediction , tf.argmax(Y, axis=1))
    accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float32))

In [37]:
    tf.summary.scalar('accuracy', accuracy)
    tf.summary.scalar('cost', loss)

<tf.Tensor 'cost:0' shape=() dtype=string>

### Check input Images In TensorBoard

In [38]:
with tf.name_scope('show_image'):
    x_image = tf.reshape(X, [-1, 28, 28, 1])
    tf.summary.image('image_input', x_image, max_outputs=4)

# <span style="color: #3A86FF; font-family: Georgia; font-size: 27px; text-shadow: 1px 1px 2px #A2D2FF">Run Session</span>

In [39]:
sess = tf.Session()

### Setup FileWriter And Merge Summaries

In [40]:
merged_summary = tf.summary.merge_all()

train_writer = tf.summary.FileWriter(directory + '/train')
train_writer.add_graph(sess.graph)

validation_writer = tf.summary.FileWriter(directory + '/validation')

### Initialise all the variables

In [41]:
# Initialise all the variables
init = tf.global_variables_initializer()
sess.run(init)

# <span style="color: #3A86FF; font-family: Georgia; font-size: 27px; text-shadow: 1px 1px 2px #A2D2FF">Batching The Data</span>

In [42]:
size_of_batch = 1000

In [43]:
num_examples = y_train.shape[0]
nr_iterations = int(num_examples/size_of_batch)

index_in_epoch = 0 

In [44]:
# we gonna get all the values between 0 and 999 why bcz we gonna suopply 1000 to the size of the batch 
# so the starting value will be the 0 then index_in_epoch will be equal to itself + 1000 
# and the ending value will be equal to 1000.
# so in this will get value between 0:1000.
def next_batch(size_of_batch, data, labels):
    global num_examples
    global index_in_epoch

    start = index_in_epoch
    index_in_epoch += size_of_batch

    if index_in_epoch > num_examples:
        start = 0
        index_in_epoch = size_of_batch

    end = index_in_epoch
    return data[start:end], labels[start:end]
    

# <span style="color: #3A86FF; font-family: Georgia; font-size: 27px; text-shadow: 1px 1px 2px #A2D2FF">Training Loop</span>

In [45]:
for epoch in range(nr_epochs):

    # =========== Training Dataset ===========
    for i in range(nr_iterations):
        batch_x, batch_y = next_batch(size_of_batch=size_of_batch, data=x_train, labels=y_train)
        feed_dictionary = {X: batch_x, Y: batch_y}  # Make sure Y is your labels placeholder
        sess.run(train_step, feed_dict=feed_dictionary)
        
        # Get summary and accuracy for the current batch
        s, batch_accuracy = sess.run(fetches=[merged_summary, accuracy], feed_dict=feed_dictionary)
        train_writer.add_summary(s, epoch * nr_iterations + i)
    
    # Calculate accuracy on the whole training set at the end of each epoch
    epoch_accuracy = sess.run(accuracy, feed_dict={X: x_train, Y: y_train})
    print(f'Epoch {epoch} \t Training Accuracy = {epoch_accuracy}')

    # =========== Validation Dataset ===========
    # Calculate accuracy on validation set at the end of each epoch
    summary, val_accuracy = sess.run(fetches=[merged_summary, accuracy], feed_dict={X: x_val, Y: y_val})
    validation_writer.add_summary(summary, epoch)
    print(f'Epoch {epoch} \t Validation Accuracy = {val_accuracy}')

print('Done training!')

Epoch 0 	 Training Accuracy = 0.8129600286483765
Epoch 0 	 Validation Accuracy = 0.8156999945640564
Epoch 1 	 Training Accuracy = 0.8392000198364258
Epoch 1 	 Validation Accuracy = 0.8357999920845032
Epoch 2 	 Training Accuracy = 0.851140022277832
Epoch 2 	 Validation Accuracy = 0.8478999733924866
Epoch 3 	 Training Accuracy = 0.858519971370697
Epoch 3 	 Validation Accuracy = 0.8555999994277954
Epoch 4 	 Training Accuracy = 0.8654199838638306
Epoch 4 	 Validation Accuracy = 0.8619999885559082
Epoch 5 	 Training Accuracy = 0.8694800138473511
Epoch 5 	 Validation Accuracy = 0.864300012588501
Epoch 6 	 Training Accuracy = 0.8733400106430054
Epoch 6 	 Validation Accuracy = 0.8662999868392944
Epoch 7 	 Training Accuracy = 0.9577800035476685
Epoch 7 	 Validation Accuracy = 0.9531000256538391
Epoch 8 	 Training Accuracy = 0.9674400091171265
Epoch 8 	 Validation Accuracy = 0.9588000178337097
Epoch 9 	 Training Accuracy = 0.9712799787521362
Epoch 9 	 Validation Accuracy = 0.9613000154495239
Epo

# Saving the Model

In [46]:
outputs = {'accuracy_calc/prediction': model_prediction}
inputs = {'x': X}
tf.compat.v1.saved_model.simple_save(sess, 'SavedModel', inputs, outputs)

Instructions for updating:
This API was designed for TensorFlow v1. See https://www.tensorflow.org/guide/migrate for instructions on how to migrate your code to TensorFlow v2.
Instructions for updating:
This API was designed for TensorFlow v1. See https://www.tensorflow.org/guide/migrate for instructions on how to migrate your code to TensorFlow v2.
INFO:tensorflow:Assets added to graph.
INFO:tensorflow:No assets to write.
INFO:tensorflow:SavedModel written to: SavedModel\saved_model.pb


# <span style="color: #3A86FF; font-family: Georgia; font-size: 33px; text-shadow: 1px 1px 2px #A2D2FF">Make a Prediction</span>

In [48]:
img = Image.open(r'C:\Users\User\mlprojects\MNIST\test_img.png')
img

In [49]:
bw = img.convert('L')

In [50]:
img_array = np.invert(bw)

In [51]:
img_array.shape

(28, 28)

In [52]:
test_img = img_array.ravel()

In [53]:
test_img.shape

(784,)

In [54]:
prediction = sess.run(fetches=tf.argmax(output, axis=1), feed_dict={X:[test_img]})

In [55]:
print (f'Prediction For Test Iamge Is{prediction}')

Prediction For Test Iamge Is[2]


# <span style="color: #3A86FF; font-family: Georgia; font-size: 36px; text-shadow: 1px 1px 2px #A2D2FF">Testing And Evaluation</span>

In [56]:
test_accuracy = sess.run(fetches=accuracy,feed_dict={X:x_test,Y:y_test })

In [57]:
print(f'Accuracy On Test Set Is {test_accuracy:0.2%}')

Accuracy On Test Set Is 97.89%


# <span style="color: #3A86FF; font-family: Georgia; font-size: 40px; text-shadow: 1px 1px 2px #A2D2FF">✨ COMPLETED ✨</span>


# <span style="color: #3A86FF; font-family: Georgia; font-size: 27px; text-shadow: 1px 1px 2px #A2D2FF">Reset For The Next Run</span>

In [2]:
train_writer.close()
sess.close()
tf.reset_default_graph()

NameError: name 'train_writer' is not defined


# <span style="color: #3A86FF; font-family: Georgia; font-size: 27px; text-shadow: 1px 1px 2px #A2D2FF">Reset For The Next Run</span>

In [ ]:
# layer1 is second hidden layer.
#with tf.name_scope('hidden_1'):

#    initial_w1 = tf.truncated_normal(shape=[TOTAL_INPUTS, n_hidden1], stddev=0.1, seed=42)
#    w1 = tf.Variable(initial_value=initial_w1, name='w1')
    
#    initial_b1 = tf.constant(value=0.0, shape=[n_hidden1])
#    b1 = tf.Variable(initial_value=initial_b1, name='b1')
    
#    layer1_in = tf.matmul(X, w1) + b1
#    layer1_out = tf.nn.relu(layer1_in)

In [ ]:
# layer2 is second hidden layer.
#with tf.name_scope('hidden_2'):

#    initial_w2 = tf.truncated_normal(shape=[n_hidden1, n_hidden2], stddev=0.1, seed=42)
#    w2 = tf.Variable(initial_value=initial_w2, name='w2')
    
#    initial_b2 = tf.constant(value=0.0, shape=[n_hidden2])
#    b2 = tf.Variable(initial_value=initial_b2, name='b2')
    
#    layer2_in = tf.matmul(layer1_out, w2) + b2 #  out put od the layer1_out is multipited by w2 and pluse bais
#    layer2_out = tf.nn.relu(layer2_in)

In [ ]:
# layer2 is second hidden layer.
#with tf.name_scope('output_layer'):
#    initial_w3 = tf.truncated_normal(shape=[n_hidden2, NR_CLASSES], stddev=0.1, seed=42)
#    w3 = tf.Variable(initial_value=initial_w3, name='w3')
    
#    initial_b3 = tf.constant(value=0.0, shape=[NR_CLASSES])
#    b3 = tf.Variable(initial_value=initial_b3, name='w3')
    
#    layer3_in = tf.matmul(layer2_out, w3) + b3 
#    output = tf.nn.softmax(layer3_in)

In [ ]:
#b1.eval(sess)

In [ ]:
#w1.eval(sess)

In [ ]:
#b3.eval(sess)